//-------------------------------------------------
//                  NAVA v1.x
//   Forward declarations - GENERATED, do not hand-edit.
//   Regenerate: python3 tools/gen_prototypes.py
//-------------------------------------------------

#ifndef prototypes_h
#define prototypes_h

boolean PatternLooksV2(byte n);
boolean RedoPop();
boolean UndoPop();
byte BankCheck(unsigned int *resumeIndex);
byte FirstBitOn();
byte NameCharIndex(char c);
byte SecondBitOn();
byte SysExDecode(const byte *src, byte n, byte *dst, byte maxOut);
byte SysExEncode(const byte *src, byte n, byte *dst);
byte TrigLenNow();
char * ActiveName();
char NameCharAt(byte i);
int EncGet(int value, int dif);
static boolean CondAllows(byte z, byte idx);
static boolean CondCyclePasses(byte c);
static boolean CondProbPasses(byte p);
static byte * CondByteAt();
static byte KeybAppendSlot();
static byte ResolveDir(int count);
static byte SelfTestByte(byte which, unsigned long addr, byte i);
static byte UtilRotatedIndex(byte p, byte lo, byte m, byte r);
static unsigned int BuildStepWord(byte s);
static unsigned long SubTicks(SubGrid *g, byte n, byte scale);
static void ActiveNameDirty();
static void EepAddr(unsigned long addr);
static void EepWaitReady(unsigned long addr);
static void EmitGroup(unsigned int w);
static void KeybNoteOff();
static void KeybNoteOn();
static void LinkSetRule(byte rule);
static void LinkSetTarget(byte ti);
static void MigrateOnePattern(byte n);
static void MigrateOneTrack(byte t);
static void RollFire();
static void SelfTestPrintAddr(unsigned long v);
static void SlaveClockReset();
static void SwingDistribute();
static void UndoAfter();
static void UndoCapture(UndoSnap *s);
static void UndoRestore(UndoSnap *s);
static void UndoSwapBytes(byte *a, byte *b, unsigned int n);
static void UtilClearGroups(byte lo, byte hi);
static void UtilClearRange(byte first, byte count);
static void UtilCopyRecord(byte from, byte to);
static void UtilMoveRange(byte first, byte count, byte dest);
static void UtilPasteRange(byte first, byte count);
static void UtilReadRecord(byte n);
static void UtilRemapTracks(byte lo, byte hi, byte m, byte r);
static void UtilWriteRecord(byte n);
unsigned int BuildCondMask(byte s);
unsigned int InstMaskFromButtons(unsigned int btns);
unsigned int InstValueGet(unsigned int value);
unsigned int MuteLedsFromMask(unsigned int mask);
unsigned int TempoShown();
void BankCheckBoot();
void BankWriteHeader(byte state, unsigned int index);
void BrowseButtons();
void BrowseEncoder();
void BrowseEnter();
void BrowseExit();
void BrowsePeek();
void ButtonGet();
void ButtonGet(Button *button, unsigned int pin);
void ButtonGetExpander();
void ClearWholePattern();
void CondButtons();
void CondEncoder();
void CondEnter();
void CondExit();
void CondNextPage();
void ConnectMidiHandleNote();
void ConnectMidiHandleRealTime();
void CopyPatternToBuffer(byte patternNum);
void CountPPQN();
void DisconnectMidiHandleNote();
void DisconnectMidiHandleRealTime();
void EepRead(unsigned long addr, byte *dst, byte n);
void EepromSelfTest();
void EepWrite(unsigned long addr, const byte *src, byte n);
void EncGet();
void EncScan();
void Expander();
void FireStep();
void GateButtonGet();
void HandleClock();
void HandleContinue();
void HandleNoteOff(byte channel, byte pitch, byte velocity);
void HandleNoteOn(byte channel, byte pitch, byte velocity);
void HandleProgramChange(byte channel, byte number);
void HandleStart();
void HandleStop();
void HandleSystemExclusive(byte *array, byte size);
void InitButtonCounter();
void InitEEprom();
void initExpTimer();
void initFlamTimer();
void InitIO();
void InitMidiNoteOff();
void InitMidiRealTime();
void InitPattern();
void InitPatternBuf(boolean buf);
void InitPatternRecord(boolean buf, byte n);
void InitSeq();
void initTrigTimer();
void InputScan();
void KeyboardUpdate();
void LaneSetParam(byte inst, byte which, byte v);
void LaneSyncAll();
void LaneSyncPhase(byte z);
void LcdBufInit();
void LcdClearLine();
void LcdDrawMsg();
void LcdFlush();
void LcdPrint2(unsigned int v);
void LcdPrint3(unsigned int v);
void LcdPrintBar(byte cells, byte filled);
void LcdPrintBpm();
void LcdPrintEEpromInit();
void LcdPrintName(const char *nm);
void LcdPrintNumbered(byte n, boolean isTrack);
void LcdPrintPasteMask();
void LcdPrintState();
void LcdPrintTempo();
void LcdPrintTM2Adjust();
void LcdPrintTotalAcc();
void LcdUpdate();
void LinkButtons();
void LinkEncoder();
void LoadPattern(byte patternNbr);
void LoadSeqSetup();
void LoadTrack(byte trackNbr);
void Metronome(boolean state);
void MidiRead();
void MidiSendNoteOff(byte channel, byte value);
void MidiSendNoteOn(byte channel, byte value, byte velocity);
void MidiTrigOff(byte inst);
void MidiTrigOn(byte inst, byte velocity);
void MigrateV1toV2(unsigned int resumeFrom);
void MuteButtonGet();
void NameCursorAdvance();
void NameEditButtons();
void NameEditEncoder();
void NameEditEnter();
void NameEditExit();
void NamePeek(byte n, boolean isTrack);
void PanelClose();
void PasteBufferToPattern(byte patternNum);
void PasteMaskInto(Pattern *d, const Pattern *s, byte m);
void PrepareNextStep();
void ResetDoutTrig();
void RevertToSaved();
void SavePattern(byte patternNbr);
void SaveSeqSetup();
void SaveTrack(byte trackNbr);
void ScanDin();
void ScanDinBoot();
void SelectFirstMux();
void SelectSecondMux();
void SendAllNoteOff();
void SeqConfiguration();
void SeqConfigurationExpander();
void SeqParameter();
void SetDacA(int velocity);
void SetDoutLed(unsigned int stepLed, unsigned int configLed, byte menuLed);
void SetDoutTrig(unsigned int value);
void setFlam();
void SetHHPattern();
void SetHHPatternBuf(boolean buf);
void SetLeds();
void SetLedsExpander();
void SetMux(byte stp);
void SetMuxCym(byte z, byte stp, boolean playing);
void SetMuxFlam(byte stp);
void SetMuxHat(byte stp, boolean playing, boolean useOh);
void SetMuxTrig(int data);
void SetMuxTrigMidi(byte inst, byte velocity);
void SetSeqSync();
void SetTrigPeriod(byte ms);
void ShiftLeftPattern();
void ShiftRightPattern();
void SysExDumpAll();
void SysExDumpPattern(byte n);
void SysExDumpSetup();
void SysExDumpTrack(byte n);
void SysExSendEnd();
void SysExSendIdentity();
void SysExSendPage(byte cmd, byte a, byte b, const byte *data);
void TimerSetFrequency();
void TimerSetPeriodUs(unsigned int us);
void TimerStart();
void TimerStop(void);
void TriggerOffTimer();
void UndoDiscard();
void UndoPush();
void UtilButtons();
void UtilEncoder();
void UtilExecute();
void WireBeginTX(unsigned long address);

#endif//prototypes_h
